GET https://keybz.netlify.app/.netlify/functions/user
###

POST https://keybz.netlify.app/.netlify/functions/user
Content-Type: application/json

{
    "username": "test3",
    "password": "test3"
}
