GET http://localhost:9000/user
###

POST http://localhost:9000/user
Content-Type: application/json

{
    "username": "test3",
    "password": "test3"
}

###
GET http://localhost:9000/user

###
POST http://localhost:9000/user
Content-Type: application/json

{
    "username": "test3",
    "password": "test3"
}
